name: ðŸ› Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please verify these steps before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of claude-flow-ui
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images or paste URLs here

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you experiencing this issue?
      options:
        - Development (localhost)
        - Staging
        - Production
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of claude-flow-ui are you running?
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser(s)
      description: Which browser(s) are you experiencing the issue on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Other

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser?
      placeholder: e.g., Chrome 120.0.0.0

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the OS?
      placeholder: e.g., Windows 11, macOS 14.2, Ubuntu 22.04

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Laptop
        - Tablet
        - Mobile Phone
        - Other

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors in the browser console?
      placeholder: Paste any console errors here...
      render: shell

  - type: textarea
    id: network-logs
    attributes:
      label: Network Issues
      description: Any network-related issues? (failed requests, timeouts, etc.)
      placeholder: Describe any network issues...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (system crash, data loss)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue, workaround available)
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this happen?
      options:
        - Always (100%)
        - Often (>50%)
        - Sometimes (10-50%)
        - Rarely (<10%)
        - Once
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a workaround for this issue?
      placeholder: Describe any workarounds you've found...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any other details that might be relevant...

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas does this bug affect? (select all that apply)
      options:
        - label: User Interface (UI)
        - label: Terminal functionality
        - label: WebSocket connections
        - label: Performance
        - label: Security
        - label: Accessibility
        - label: Mobile experience
        - label: Data integrity
        - label: Authentication/Authorization
        - label: API functionality

  - type: textarea
    id: user-agent
    attributes:
      label: User Agent String
      description: Your browser's user agent string (optional but helpful)
      placeholder: Paste your user agent string here...
      render: text